### PR TITLE
Initial draft of Intersection Observer post

### PR DESCRIPTION
**Pull request by rorticus**
Blog post for Intersection Observer and how to use it for simple visibility testing in Dojo 2.

### CODE REVIEW

**Comment by rorticus** [comment]
I should probably go into more depth on what values the `Intersection` meta actually returns but I didn't want to make it more confusing than it has to be.

Do you think it'd be worth adding an example of maybe a headline that animates into view as you scroll? That would show off the `intersectionRatio` options..

**Comment by dylans** [comment]
I think this one kind of misses on some of the coolest things, namely that we're providing Intersection Observers in a manner that preserves a reactive, virtual dom based approach. It also feels a bit too cute... the style here is closer to what we might do at sitepen.com, but on dojo.io in general we try to be a bit more direct/no nonsense given the wide range of people reading the site. I do think the more examples we have showing things off the better. I'm wondering if we should have a separate sitepen blog similar to the resize observer post, and then have this one just explain the Dojo 2 usage of Intersection Observer? cc @JamesMilnerUK for his thoughts as well.

**Comment by JamesMilnerUK** [comment]
I generally agree with Dylan, but here are some general points from my end:

- I think it'd benefit from a sentence on why images and page weight are bad for users
- Maybe an explanation of what lazy loading is? Might help with beginners

I really liked the code samples :smile:, I thought those were very clear.

**Comment by rorticus** [comment]
Closing this because its kind of old 😂

**Pull request closed without merging**
