### PR TITLE
Site updates

### PR DESCRIPTION
**Pull request by vansimke**
This PR contains the site updates that start to prepare the way for the creation of the reference-guide section and tutorial sub-categories

### CODE REVIEW

**Comment by dylans** [comment]
@vansimke has merge conflicts with the actual tutorial content, so I would suggest splitting those changes.

**Comment by vansimke** [comment]
@dylans I think the conflicts are coming from updates to the front-matter, which is part of the site-update. If you'd like, I can rebase onto master so that there won't be any conflicts in this PR.

**Comment by dylans** [comment]
@vansimke yes, let's rebase onto master please. Thanks!

**Comment by vansimke** [comment]
@dylans I've finished the rebase, but it would be good to have someone else do a full rebuild and review of the site. There were many conflicts to resolve and so another pair of eyes would be advisable to protect against regressions.

**Comment by edhager** [comment]
This PR has been un-landed.  https://github.com/dojo/dojo.io/tree/broken-api contains the squashed commit from @vansimke's branch.  The API pages in that branch do not work.  It is the same issue I saw in my local build environment.  Due to the complicated nature of the build, I thought it was an issue in my environment.  Apparently not.

**Pull request merged**
